name: Publish Python Package

on:
  release:
    types: [published]

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install uv (for fast dependency management)
        run: pip install uv

      - name: Install project and development dependencies
        run: uv pip install -e ".[dev]"

      - name: Run formatter with Poe
        run: uv run poe format

      - name: Run linter with Poe
        run: uv run poe lint

      - name: Run tests with Poe
        run: uv run poe test

      - name: Build package distribution files
        run: uv run python -m build

      - name: Upload distributions as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  pypi-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build_and_test

    permissions:
      id-token: write

    environment:
      name: pypi
      url: https://pypi.org/p/webshocket

    steps:
      - name: Download distributions from build job
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
