name: Python Package CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

      matrix:
        python-version: ["3.8", "3.10", "3.12", "3.13"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install uv
        run: pip install uv

      - name: Install dependencies with uv
        run: uv pip install -e ".[dev]"

      - name: Run formatter with Poe
        run: uv run poe format

      - name: Run linter with Poe
        run: uv run poe lint

      - name: Run tests with Poe
        run: uv run poe test
